### ISSUE TITLE
TagSearch Timeout

### ISSUE THREAD

**Issue by rufutecharasu** [cslrfid/CS108-iOS-ObjC-App#20]
I have used the demo app code to search a tag. Below is the code I"m using to start tag search.

TagData = "ABC000000000000000000223"

`[[CSLRfidAppEngine sharedAppEngine].reader startTagSearch:EPC maskPointer:32 maskLength:((UInt32)self.tagData.length * 4) maskData:[CSLBleReader convertHexStringToData:self.tagData]]`

After initiating the start tag, i'm getting result as NO, with timeout error.
But successfully getting values in delegate methods, but this should not happen.
Please fix the issue in library, Because of which UI also distorted.

Thanks

**Comment by ksclam** [comment]
You command is okay and the please make sure that the reader is not doing and other read/write operation when tag search function is being called.  This might cause result=NO and a timeout.

After calling the tag search function, the delegate method would return CSLBleTag on each of the reading, and there would some filtering needed on the application (circular buffer that holds the filtering time window).  All of these are being demonstrated on the demo app.  If you run straight from the demo app and find no problem, you should be able to achieve the same on your code.

**Comment by rufutecharasu** [comment]
@ksclam : I'm trying from demo app only. This happens directly going to find a tag.

**Comment by ksclam** [comment]
Please launch the demo app and go to the "About" page.  After that, look at the line "RFID firmware version" and see if you can retrieve the RFID firmware version.  If you are getting a blank field on this, please reflash the reader with the latest RFID firmware again.

**Comment by rufutecharasu** [comment]
Let me check it. 

But the same thing never happens in AppStore Version 🤔  

How do I refresh reader?
I'm trying to upgrade firmware. but it gives me an error(PFA)

![image](https://user-images.githubusercontent.com/51223664/62860062-a6ff6480-bd1c-11e9-91f8-ae0bfc6f89c9.png)
![image](https://user-images.githubusercontent.com/51223664/62860067-a9fa5500-bd1c-11e9-80eb-525b0b073e3f.png)

**Comment by ksclam** [comment]
The cause is unknown at the moment but we are trying to determine the root cause of this.

If you launch the upgrade tool, please select "upgrade image" and pick the latest file you download from the other GitHub repos:

https://github.com/cslrfid/CS108-Product-Downloads/tree/master/Firmware/Firmware%20-%20RFID%20Processor

**Comment by rufutecharasu** [comment]
> The cause is unknown at the moment but we are trying to determine the root cause of this.
> 
> If you launch the upgrade tool, please select "upgrade image" and pick the latest file you download from the other GitHub repos:
> 
> https://github.com/cslrfid/CS108-Product-Downloads/tree/master/Firmware/Firmware%20-%20RFID%20Processor

Yes. I tried it, I have already provide screenshot of it. Same error only occurs.

**Comment by ksclam** [comment]
If you launch the demo app and get connected to the reader.  Then, go to the "About" page and look at the line "RFID firmware version".  What do you see?

**Comment by rufutecharasu** [comment]
![image](https://user-images.githubusercontent.com/51223664/62996361-1c387a00-be82-11e9-9170-53455df5feef.png)

**Comment by ksclam** [comment]
As this is related hardware/firmware, please kindly provide your email sending a message to info@convergence.com.hk <mailto:info@convergence.com.hk>.  We will further assist on this through email.

Thanks.
