### ISSUE TITLE
Allow Alphanumeric characters input in EPC value

### ISSUE THREAD

**Issue by kirankumarg99** [cslrfid/CS108-iOS-ObjC-App#22]
In the CS108 RFID reader after reading the RFID Chips we get the Series Number and Serial Number . Currently the Series Number and Serial Number textfield allows only 0123456789ABCDEF these character range. But my requirement is to allow all the alphanumeric characters(Series Number and Serial Number) Series Number and Serial Number text fields.
Could you please help me in achieving this. Also please let me know where all should change the values.
Please help me in providing some coding examples.

**Comment by ksclam** [comment]
There is a routine inside the code for converting the tag value in hex to ascii (alphanumeric).  You can copy it over to the inventory page for displaying tag data in ascii.

- (NSString *)asciiStringFromHexString:(NSString *)hexString;

**Comment by kirankumarg99** [comment]
I am not able to write to the chip even after using your routine:
asciiStringFromHexString.
Please provide me a coding example for this.
Also, please clarify me what is the input value(is it hex string or ascii string) to be passed for EPC to support Alphanumeric characters for writing & reading on the RFID chip.
