### ISSUE TITLE
Forced disconnect from device on iOS 

### ISSUE THREAD

**Issue by wrightwoldscientific** [cslrfid/CS108-iOS-ObjC-App#9]
I realize this may be out of the scope of this repo, but I am having trouble maintaining a connection to the CS108 device from the app I am developing on iOS.
I am developing a Nativescript app on android and iOS with the Nativescript-bluetooth plugin (https://github.com/eddyverbruggen/nativescript-bluetooth). 
The app will connect and read for 30 s to a minute after I set it to start notifying (9901) and then start inventory commands. If I set start notifying only and do not initiate the start inventory method I can stay connected forever. As soon as I start inventory then the issue arises. Did you run into this issue when developing the ios version, if so how do you overcome it?

on a side note, I realize it is possible that this is an error in the way the nativescript-bluetooth plugin interacts with ios CB parameters, but if i can verify where the issues is I can modify the plugin to fix.

Also here is some console output below:
error	10:28:40.171903 -0500	bluetoothd	Timeout waiting for ATT response, forcing a disconnect. (status=65535)
default	10:28:40.173413 -0500	bluetoothd	-Topology------------
default	10:28:40.174816 -0500	bluetoothd	LE [<private> 0x41], [interval 37 latency 0 CE 12], [Tx 27 Rx 27], MASTER, Ready 6(LE_READY_IDLE), State 7(DISCONNECTED), Enc OFF LSTO 500
default	10:28:40.175792 -0500	bluetoothd	---------------------
default	10:28:40.209949 -0500	bluetoothd	LE Link disconnected for handle 0x107d00ee0 address <private> with reason 722
default	10:28:40.211476 -0500	bluetoothd	 _GATT_LE_DisconnectedCB on handle 0x0000000107D00EE0 with reason  STATUS 722
default	10:28:40.212427 -0500	bluetoothd	 Releasing LE connection 0x0041
default	10:28:40.213531 -0500	bluetoothd	LE ConnManager disconnection complete reason 722 address=<private> localRole=Master
default	10:28:40.214880 -0500	powerd	Process bluetoothd.74 Released PreventUserIdleSystemSleep "com.apple.BTStack" age:00:02:18  id:4295001839 [System: SysAct]
default	10:28:40.216189 -0500	bluetoothd	Device "96310355-1A2E-2371-2F87-75D1D0C2933B" set last connected time to 1542968920
default	10:28:40.246619 -0500	bluetoothd	Found link-ready device calling disconnection notification
default	10:28:40.247239 -0500	bluetoothd	Disconnected from device "96310355-1A2E-2371-2F87-75D1D0C2933B" successfully (locally-initiated)
default	10:28:40.247632 -0500	bluetoothd	disconnectNotificationRequired:1 disconnectDevice:0 localRole:0 reason:722 result:0
default	10:28:40.247942 -0500	bluetoothd	Sending 'connection status changed' event to local device listeners
default	10:28:40.248272 -0500	bluetoothd	Sending 'connection state updated' event for device "<private>" to session "com.apple.wirelessproxd-central-55-0"
default	10:28:40.248578 -0500	bluetoothd	Sending XPC message "CBMsgIdPeripheralConnectionStateUpdated" to session "com.apple.wirelessproxd-central-55-0"
default	10:28:40.248907 -0500	bluetoothd	Dispatching connection status update for device "<private>" to session "org.nativescript.SwiftCENSUS-central-391-43"
default	10:28:40.249238 -0500	bluetoothd	Sending XPC message "CBMsgIdPeripheralDisconnectionCompleted" to session "org.nativescript.SwiftCENSUS-central-391-43"
default	10:28:40.249662 -0500	SpringBoard	Bluetooth connection status changed
default	10:28:40.250107 -0500	SpringBoard	Number of connectedDevices that may be blacklisted : 0
default	10:28:40.250553 -0500	SpringBoard	Bluetooth state updated to connected [ inoperative: 0 enabled: 0 useAlternateBackground: 1 subtitle: <private> ]
default	10:28:40.250849 -0500	SpringBoard	[SBTelephonyManager Slot 1]: updated data connection type -- manager: <SBTelephonyManager: 0x2802bd450> {
    dualSIMEnabled = NO;
    slot1SubscriptionInfo = <SBMutableTelephonySubscriptionInfo: 0x28171ac00> {
        SIMStatus = kCTSIMSupportSIMStatusReady;
        registrationStatus = registered;
        dataConnectionType = wifiConnection;
        signalStrengthBars = 4;
        isPreferredForDataConnections = YES;
        isProvidingDataConnection = YES;
        operatorName = "U.S. Cellular";
    };
    slot2SubscriptionInfo = <SBMutableTelephonySubscriptionInfo: 0x28171ad00> {
        SIMStatus = 0x0;
        registrationStatus = notRegistered;
        dataConnectionType = wifiConnection;
        signalStrengthBars = 0;
        isPreferredForDataConnections = NO;
        isProvidingDataConnection = NO;
        operatorName = 0x0;
    };
    usingWifi = YES;
}
default	10:28:40.252937 -0500	bluetoothd	handleDisconnectionCompleteCallback skipping processConnectingList, processConnectingList=0, LE Connection Manager State is Active
default	10:28:40.253200 -0500	bluetoothd	Gatt device disconnected on handle 0x107d00ee0 with status 722
default	10:28:40.253491 -0500	bluetoothd	GattGateway device "96310355-1A2E-2371-2F87-75D1D0C2933B" is disconnected
default	10:28:40.254185 -0500	SpringBoard	[SBTelephonyManager Slot 2]: updated data connection type -- manager: <SBTelephonyManager: 0x2802bd450> {
    dualSIMEnabled = NO;
    slot1SubscriptionInfo = <SBMutableTelephonySubscriptionInfo: 0x28171ac00> {
        SIMStatus = kCTSIMSupportSIMStatusReady;
        registrationStatus = registered;
        dataConnectionType = wifiConnection;
        signalStrengthBars = 4;
        isPreferredForDataConnections = YES;
        isProvidingDataConnection = YES;
        operatorName = "U.S. Cellular";
    };
    slot2SubscriptionInfo = <SBMutableTelephonySubscriptionInfo: 0x28171ad00> {
        SIMStatus = 0x0;
        registrationStatus = notRegistered;
        dataConnectionType = wifiConnection;
        signalStrengthBars = 0;
        isPreferredForDataConnections = NO;
        isProvidingDataConnection = NO;
        operatorName = 0x0;
    };
    usingWifi = YES;
}
default	10:28:40.256705 -0500	bluetoothd	Clearing database cache for device "<private>"
default	10:28:40.258528 -0500	bluetoothd	GATT Device <private> connected
default	10:28:40.258873 -0500	bluetoothd	Dispatching GATT device disconnected for device "<private>" to session "com.google.Maps-central-194-18"

Thanks!

**Comment by ksclam** [comment]
I assume you are trying to establish BLE connection with the reader and sending commands and receiving notifications, directly from the the Nativescript code with the Bluetooth plug-in.  In other words, you are not reusing the Obj-C code on this repos.  Please correct me if I am wrong.  

It might be easier to access the obj-c classes on this repos natively from your code so that you are save some effort on handling the lower-level BLE communication.  That is what we have been trying to do achieve.

Let us review logic flow of your code and get back to you.  Thanks and happy coding.

**Comment by wrightwoldscientific** [comment]
Found this issue here. The rfid power on command was within the notify callback from the Bluetooth plugin and this caused it to repeatedly send the power on command to the reader, which for some reason caused a disconnect from Bluetooth as far as I could tell. Once those pieces of code were appropriately separated it functioned well. We are working on processing inventory packets in compact mode now. Taking note on how you made a circular queue in your app. Is there documentation on how you should set parameters for a specific application? Or could you give us some suggestions. We essentially are reading a room full of tags on the order of hundreds at relatively long range (1 m to 6 m) with various read angles, and we’d like it to be as fast and efficient as possible. We can talk outside of github as well as this doesn’t necessarily pertain to your app. My email is zachary.wright@swiftagsystems.com. Thanks!
